# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  workflow_dispatch:
  push:

jobs:

  build:
  
    runs-on: windows-latest
    
    steps:
    
    - uses: actions/checkout@v4
      with:
        # _____                         _____                           _              _   
        #/  ___|                       |_   _|                         | |            | |  
        #\ `--. _   _ _ __   ___ _ __    | | _ __ ___  _ __   ___  _ __| |_ __ _ _ __ | |_ 
        # `--. \ | | | '_ \ / _ \ '__|   | || '_ ` _ \| '_ \ / _ \| '__| __/ _` | '_ \| __|
        #/\__/ / |_| | |_) |  __/ |     _| || | | | | | |_) | (_) | |  | || (_| | | | | |_ 
        #\____/ \__,_| .__/ \___|_|     \___/_| |_| |_| .__/ \___/|_|   \__\__,_|_| |_|\__|
        #            | |                              | |                                  
        #            |_|                              |_|                                  
        # include tag metadata in the checkout so we can query it successfully with git commands
        fetch-depth: 0
        fetch-tags: true

    - name: Install Go v1.24.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Install go-winres (.exe file-version resource stamper)
      run: go install github.com/tc-hib/go-winres@latest

    - name: Build (and generate script variables)
      id: buildAsset
      run: |
        # this is copied straight from release builder's previous-tag query logic but doing here to generate new release number by +1'ing the previous release tag
        # https://github.com/mikepenz/release-changelog-builder-action/blob/9d5249982e67893edf0382587243ff5fb50580c2/src/pr-collector/gitHelper.ts#L21

        # how to create *step output variables* in pwsh: https://stackoverflow.com/questions/69099977/using-outputs-of-powershell-in-github-actions/75630489#75630489
        $lastRelease="$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=0 --max-count=1))"
        Write-Output "fromTag=$($lastRelease)" >> $Env:GITHUB_OUTPUT

        # start with incrementing the semver which has 3 pieces: 1.0.x
        $newReleaseSemVer="1.0.$([int]$lastRelease.split(".")[2]+1)"
        # create windows file version which has 4 pieces: 1.0.x.0
        $windowsFileVersion="$($newReleaseSemVer).0"
        Write-Output "newReleaseTag=v$($newReleaseSemVer)" >> $Env:GITHUB_OUTPUT

        # go ahead and bake in the windows product version which can have characters vs just numbers: v1.0.x.0
        go-winres make --file-version=$windowsFileVersion --product-version=v$windowsFileVersion
        go build -ldflags "-X main.version=$($newReleaseSemVer)" -v ./...

    # https://github.com/marketplace/actions/release-changelog-builder
    - name: Generate release notes (from commits since last release)
      id: releaseNotes
      uses: mikepenz/release-changelog-builder-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        mode: "COMMIT" # "COMMIT" mode builds release notes as a bulleted list of commit messages since the **previous** release **tag**
        outputFile: notes.md

    # gh command reference: https://cli.github.com/manual/
    - name: Create release (with new exe and build notes attached)
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      # the first argument to `gh release create` is the TAG that will be created and applied to this new release
      run: |
        gh release create ${{ steps.buildAsset.outputs.newReleaseTag }} pids.exe --notes-file notes.md      
